# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fceb610f09a02a8269fb8af20b004f88f7774d213496b45dd9940e4527299ee7efee37ed67bd2da78924474fd5685a5171bafaf05af4fe16d98b7c96288fc3b

test:
  secret_key_base: 68e5ce7d98bc94ca9fdc81c3027303d2dad9d65f015993cd43e698e9a8837273dae74e8b57da6d8510ec073d463a2135071e81a62548e8ead9d8725f469cbe23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
